version: '2'

services:
  tmweb:
    image: httpd:alpine
    restart: unless-stopped
    network_mode: host
    depends_on:
      - tmapp
    volumes:
      - "./transmart-web/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf"
      - "./transmart-web/httpd.conf:/usr/local/apache2/conf/httpd.conf"
  tmapp:
    image: dennyverbeeck/transmart-app:tmf-16.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:8009:8009"
    depends_on:
      - tmdb
      - tmsolr
      - tmgwava
    volumes:
      - "./transmart-app/Config.groovy:/root/.grails/transmartConfig/Config.groovy"
      - "./transmart-app/DataSource.groovy:/root/.grails/transmartConfig/DataSource.groovy"
      - "./transmart-app/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
      - "appdata:/root/.grails"
      - "apptmp:/tmp"
      - "appwebapps:/usr/local/tomcat/webapps"
  tmgwava:
    image: dennyverbeeck/transmart-gwava:tmf-16.2
    restart: unless-stopped
  tmdb:
    image: dennyverbeeck/transmart-db:tmf-16.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql"
      - "postgreslogs:/var/log/postgresql"
  tmsolr:
    image: dennyverbeeck/transmart-solr:tmf-16.2
    restart: unless-stopped
  tmrserve:
    image: dennyverbeeck/transmart-rserve:tmf-16.2
    restart: unless-stopped
    volumes:
      - "apptmp:/tmp"
      - "appwebapps:/usr/local/tomcat/webapps"
  tmload:
    image: dennyverbeeck/transmart-load:tmf-16.2
    depends_on:
      - tmdb

volumes:
  appdata:
  apptmp:
  appwebapps:
  postgresdata:
  postgreslogs:
